---
title: "Positive Rolling Day Averages"
author: "Katy Seiter"
date: "9/21/2020"
output: html_document
---

```{r setup, include=FALSE}
#install.packages("zoo")
library(zoo)        
library(tidyverse)
library(rio)
```
# Replace line 160 of Daily Update with this
``` {r}
mastertest <- master2 %>% 
  select("county_nam","mydate","deaths","fhwa_numbe","fips","positive","negative","recoveries","total_tests","active_cases","pop_5yr_est_2018","confirmed_pos","probable_pos","confirmed_neg","probable_neg","confirmed_recov","probable_recov","confirmed_death","probable_death","confirmed_active","probable_active","pcr_test","antigen_test","pcr_pos_test", "pcr_neg_test","antigen_pos_test","antigen_neg_test","total_pos_test","total_neg_test", "New_Cases_Today","Recovered_Since_Yesterday","New_Deaths_Today","New_Tests_Dashboard","Cases_Population","Tested_Population","New_Cases_Today_10k_Pop","Active_Cases_10k_Pop","Pct_Positive_Cumulative","Pct_Positive_New_to_Dashboard","Closed","Pct_Deaths_vs_Recoveries","Pct_Recoveries_vs_Deaths","lab_prvt","lab_pub") %>% 
   dplyr::mutate(positive05da = zoo::rollmean(positive, k = 5, fill = NA)) %>% 
  dplyr::ungroup()
```



#The rest of this is just in case you want standalone rolling averages.

#Import data
```{r}
master_file <- rio::import("master_file.csv")
```

#Normal calculations
```{r}
rollingavg <- master_file %>%
    dplyr::arrange((mydate)) %>% 
    dplyr::group_by(mydate) %>% 
    dplyr::mutate(positive03da = zoo::rollmean(positive, k = 3, fill = NA),
                  positive05da = zoo::rollmean(positive, k = 5, fill = NA),
                  positive10da = zoo::rollmean(positive, k=10, fill = NA)) %>% 
  dplyr::ungroup()
``` 

#Calculations with date and column cuts
```{r}
rollingavgcuts <- master_file %>%
    filter(mydate >= as.Date("2020-09-13")) %>%
    select(county_nam, mydate, positive) %>% 
    dplyr::arrange((mydate)) %>% 
    dplyr::group_by(mydate) %>% 
    dplyr::mutate(positive03da = zoo::rollmean(positive, k = 3, fill = NA),
                  positive05da = zoo::rollmean(positive, k = 5, fill = NA),
                  positive10da = zoo::rollmean(positive, k=10, fill = NA)) %>% 
  dplyr::ungroup()
``` 

#Filter for specific county name and/or rolling day average
```{r}
master_file2 %>% 
  dplyr::arrange(mydate) %>% 
  dplyr::filter(county_nam == "Arkansas_all_counties") %>% 
  dplyr::select(county_nam,
                mydate,
                positive,
                positive05da)

# To look at all rolling averages for a specific county:
# master_file2 %>% 
#  dplyr::arrange(mydate) %>% 
#  dplyr::filter(county_nam == "Arkansas_all_counties") %>% 
#  dplyr::select(county_nam,
#                mydate,
#                positive,
#                positive03da:positive010da)

``` 

#Optional: Separate rolling day averages files
```{r}
TenDayRoll <- master_file2 %>% 
  select(county_nam, mydate, positive, positive10da)
FiveDayRoll <- master_file2 %>% 
  select(county_nam, mydate, positive, positive05da)
ThreeDayRoll <- master_file2 %>% 
  select(county_nam, mydate, positive, positive03da)

# write.csv(TenDayRoll, "10dayrollingavg.csv")
# write.csv(FiveDayRoll, "5dayrollingavg.csv")
# write.csv(ThreeDayRoll, "3dayrollingavg.csv")
```

